# Generated by Django 5.0.4 on 2024-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usercrypto_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercrypto',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
