# Generated by Django 5.0.4 on 2024-09-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pfp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
    ]
