# Generated by Django 5.0.4 on 2024-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_pfp_remove_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
